name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          
    - name: Cache Nix
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Install dependencies
      run: |
        nix develop . -c yarn install

    - name: Tests
      run: |
        nix develop . -c yarn run test
